### PR TITLE
Implement Gmail API (email push notifications)

### PR DESCRIPTION
**Pull request by yuna878**
## Overview

Enable email notifications

## Changes Made

Sendgrid -> Gmail API

## Test Coverage

Manual testing with local server & my phone

## Next Steps (delete if not applicable)

After deploying, gotta test if notifications work properly

### CODE REVIEW

**Review by alanna-zhou — APPROVED** [review]
wowwwwwww youre amazing :o

**Review by katesliang — APPROVED** [review]
nice!!!

**Review by tedim52 — APPROVED** [review]
LGTM. Curious, why the switch from Sendgrid to Gmail API?

**Comment by alanna-zhou** [comment]
> LGTM. Curious, why the switch from Sendgrid to Gmail API?

sendgrid expensive, gmail free

**Pull request merged**
